### ISSUE TITLE
Current version does not appear to match the 12 digit format expected

### ISSUE THREAD

**Issue by kvellano** [cwmcbrewster/Adobe#2]
Recently noticed our Jamf policy is failing with:

Current version does not appear to match the 12 digit format expected

Tested in both Intel and Silicon macOS 12

**Comment by sjbarkey** [comment]
Slight correction, we tweaked the script to allow for 12 digits, but the original, untweaked script was failing with:

Current version does not appear to match the 10 digit format expected

**Comment by cwmcbrewster** [comment]
Fixed. I reverted to the previous method of getting the current version.
